---
name: Continuous Integration

on:
  push: {}
  # At 03:12 on Monday
  schedule:
    - cron: '12 3 * * 1'

env:
  project_dir: ansible_collections/avinode/devenv

jobs:
  common-checks:
    name: Common checks (sanity, unit, integration tests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.project_dir }}

      - name: Install latest version of Ansible in a Python venv
        working-directory: ${{ env.project_dir }}
        run: scripts/setup-local-ansible.sh

      - name: Sanity checks
        working-directory: ${{ env.project_dir }}
        run: |
          .venv/bin/ansible-test sanity --color --docker default \
              --exclude scripts/setup-local-ansible.sh \
              --exclude scripts/setup-macports.sh \
              --exclude .gitignore

      - name: Unit tests
        working-directory: ${{ env.project_dir }}
        run: .venv/bin/ansible-test units --color --docker default

      - name: Integration tests (Debian)
        working-directory: ${{ env.project_dir }}
        run: |
          .venv/bin/ansible-test integration --color \
            --docker 'geerlingguy/docker-debian10-ansible:latest' \
            --python-interpreter /usr/bin/python3

      - name: Integration tests (Ubuntu 2004)
        working-directory: ${{ env.project_dir }}
        run: |
          # Replace with 'geerlingguy/docker-ubuntu2004-ansible:latest' when
          # 'pycairo' is fixed:
          #   - https://github.com/geerlingguy/docker-ubuntu2004-ansible/issues/15
          .venv/bin/ansible-test integration --color \
            --docker 'ubuntu2004' \
            --python-interpreter /usr/bin/python3

  integration-test-macports:
    name: Macports integration tests
    needs:
      - common-checks
    runs-on: ${{ matrix.MACOS_WORKER_VERSION }}
    strategy:
      matrix:
        MACOS_WORKER_VERSION:
          - macos-10.15
          #- macos-11.0  # FIXME - Still in private preview (https://github.com/actions/virtual-environments).
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.project_dir }}

      - name: Install MacPorts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ env.project_dir }}
        run: scripts/setup-macports.sh

      - name: Add MacPorts to the build PATH
        working-directory: ${{ env.project_dir }}
        run: |
          echo '/opt/local/sbin' >> $GITHUB_PATH
          echo '/opt/local/bin' >> $GITHUB_PATH
          echo '/opt/local/libexec/gnubin' >> $GITHUB_PATH

      - name: System information
        working-directory: ${{ env.project_dir }}
        run: |
          echo PATH="$PATH"

      - name: Install latest version of Ansible in a Python venv
        working-directory: ${{ env.project_dir }}
        run: scripts/setup-local-ansible.sh

      - name: Run Ansible integration tests
        working-directory: ${{ env.project_dir }}
        run: |
          .venv/bin/ansible-test integration \
              --allow-destructive \
              --allow-root \
              --color \
              --local \
              --python-interpreter /usr/bin/python3
...
